-- Enumerated types for attributing voiceover lines. Each line can have a single type or a table of types,
-- in addition to a single attitude or table of attitudes. These are mainly used for selecting a random sound from
-- a wider list.

local voTypes =
{
	ABILITY					=	'ABILITY',
	ALLY					=	'ALLY',
	ATTACK					=	'ATTACK',
	BEGINNINGBATTLE			=	'BEGINNINGBATTLE',
	BOTTLE					=	'BOTTLE',
	COOLDOWN				=	'COOLDOWN',
	COSMETIC				=	'COSMETIC',
	CURSE					=	'CURSE',
	DAMAGE					=	'DAMAGE',
	DEATH					=	'DEATH',
	DENY					=	'DENY',
	DRAFTING				=	'DRAFTING',
	ENTERINGBATTLE			=	'ENTERINGBATTLE',
	FAILURE					=	'FAILURE',
	HEROSELECT 				=	'HEROSELECT',
	IDLE					=	'IDLE',
	INTHEBAG				=	'INTHEBAG',
	ITEM					=	'ITEM',
	KILL					=	'KILL',
	LASTHIT					=	'LASTHIT',
	LAUGH					=	'LAUGH',
	LEVEL					=	'LEVEL',
	LOADOUT					=	'LOADOUT',
	LOSE					=	'LOSE',
	MANA					=	'MANA',
	MISC 					=	'MISC',
	MISS					=	'MISS',
	MOVE					=	'MOVE',
	ORDER					=	'ORDER',
	RARE 					=	'RARE',
	RESPAWN					=	'RESPAWN',
	RESPONSE				=	'RESPONSE',
	RIVAL					=	'RIVAL',
	RUNE					=	'RUNE',
	SELECT					=	'SELECT',
	TAUNT					=	'TAUNT',
	THANK					=	'THANK',
	THANKS					=	'THANK',
	WIN						=	'WIN',
}
return voTypes