-- sound constants

local sounds =
{
	-- Effects
	FIRECRACKER				= 'soundboard.new_year_firecrackers',
	MATCH_READY				= 'Stinger.MatchReady',
	ATTENTION				= 'soundboard.rimshot',
	BEEP					= 'DotaSOS.TestBeep',
	ROSHAN					= 'Roshan.Death',
	SAD_TROMBONE			= 'soundboard.sad_bone',
	GROAN					= 'soundboard.ti9.crowd_groan',
	APPLAUSE				= 'soundboard.applause',
	CHEAT					= 'Loot_Drop_Stinger_Short',
	-- English Casters (or Glados)
	HOLY_MOLY				= 'soundboard.holy_moly',
	PATIENCE				= 'soundboard.patience',
	ALL_DEAD				= 'soundboard.all_dead',
	WOW						= 'soundboard.wow',
	BRUTAL					= 'soundboard.brutal',
	PLAYING_TO_WIN			= 'soundboard.playing_to_win',
	QUESTIONABLE			= 'soundboard.that_was_questionable',
	WHAT_HAPPENED			= 'soundboard.what_just_happened',
	HERO					= 'soundboard.youre_a_hero',
	PERFECT					= 'soundboard.absolutely_perfect',
	DISAPPOINTED			= 'soundboard.glados.disappointed',
	LOOKING_SPICY			= 'soundboard.looking_spicy',
	COMING_THROUGH			= 'soundboard.coming_through_with_the_woooo',
	NOTHING_THAT			= 'soundboard.nothing_that_can_stop_this_man',
	OH_MY_GOD				= 'soundboard.oh_my_god_what_oh_oh',
	SEE_YOU_LATER			= 'soundboard.see_you_later_nerds',
	WHAT_THE_F				= 'soundboard.what_the_f_just_happened',
	-- Asian Casters
	TIAN_HUO				= 'soundboard.tian_huo',
	WAN_BU					= 'soundboard.wan_bu_liao_la',
	JIA_YOU					= 'soundboard.jia_you',
	PO_LIANG				= 'soundboard.po_liang_lu',
	ZOU_HAO					= 'soundboard.zou_hao_bu_song',
	GAO_FU					= 'soundboard.gao_fu_shuai',
	DUIYOU_NE				= 'soundboard.duiyou_ne',
	HU_LU_WA				= 'soundboard.hu_lu_wa',
	LIU_LIU_LIU				= 'soundboard.liu_liu_liu',
	NI_QI					= 'soundboard.ni_qi_bu_qi',
	LAKAD					= 'soundboard.ta_daaaa',
	OY_OY_OY				= 'soundboard.oy_oy_oy',
	NEXT_LEVEL				= 'soundboard.next_level',
	EASIEST_MONEY			= 'soundboard.easiest_money',
	ECHO_SLAMA				= 'soundboard.echo_slama_jama',
	ZAI_JIAN				= 'soundboard.zai_jian_le_bao_bei',
	LIAN_DOU				= 'soundboard.lian_dou_xiu_wai_la',
	PIAO_LIANG				= 'soundboard.piao_liang',
	BAI_TUO					= 'soundboard.bai_tuo_shei_qu',
	GAN_MA					= 'soundboard.gan_ma_ne_xiong_di',
	GOODNESS_GRACIOUS		= 'soundboard.goodness_gracious',
	NAKUPUUU				= 'soundboard.nakupuuu',
	WHATS_COOKING			= 'soundboard.whats_cooking',
	AY_AY_AY_CN				= 'soundboard.ay_ay_ay_cn',
	HUI_TIAN				= 'soundboard.hui_tian_mie',
	LAI_NI					= 'soundboard.lai_ni_da',
	NI_XING					= 'soundboard.ni_xing_ni',
	WO_SHI					= 'soundboard.wo_shi_yi',
	TIAO_ZOU				= 'soundboard.tiao_zou_le',
	-- CIS Casters
	AY_AY_AY				= 'soundboard.ay_ay_ay',
	RUSSIAN_REKT			= 'soundboard.eto_prosto_netchto',
	EHTO_GG					= 'soundboard.ehto_g_g',
	BOZHE_TI				= 'soundboard.bozhe_ti_posmotri',
	OY_OY					= 'soundboard.oy_oy_bezhat',
	ETO_SOCHNO				= 'soundboard.eto_sochno',
	KRASAVCHIK				= 'soundboard.krasavchik',
	BOZHE_KAK				= 'soundboard.bozhe_kak_eto_bolno',
	ETO						= 'soundboard.eto_nenormalno',
	KREASA					= 'soundboard.kreasa_kreasa',
	KAK_BOYGE				= 'soundboard.kak_boyge_te_byechenya',
	ETO_GE					= 'soundboard.eto_ge_popayx_feeda',
	WOT_ETO					= 'soundboard.wot_eto_bru',
	DA_DA_DA_NYET			= 'soundboard.da_da_da_nyet',
	A_NET					= 'soundboard.a_net_net_da',
	A_NU					= 'soundboard.a_nu_ka_idi_suda',
	AAAH_AAAH				= 'soundboard.aaah_aaah_chto',
	CHTO_ETO				= 'soundboard.chto_eto_kakaya_zhest',
	ETO_TAKAYA				= 'soundboard.eto_takaya_dushka',
	AKAYA					= 'soundboard.takaya_haliava',
	-- DOTA PLUS / DRAGON'S BLOOD / MISC
	LETMEIN					= 'soundboard.ddb_let_me_in',
	RUNMOUSE				= 'soundboard.ddb_run_little_mouse',
	BRAVE					= 'soundboard.ddb_stupid_brave',
	DYLM					= 'soundboard.ddb_do_you_love_me',
	DYLM2					= 'soundboard.ddb_do_you_love_me_2',
	FORM					= 'soundboard.ddb_form_up',
	PAPA					= 'soundboard.ddb_isnt_it_magical_papa',
	WISE					= 'soundboard.ddb_very_wise',
	DEATH					= 'soundboard.ddb_death',
	FEAR					= 'soundboard.ddb_fear_calls',
	ETERNITY				= 'soundboard.ddb_for_eternity',
	GOOD					= 'soundboard.ddb_good_can_come_of_this',
	MONSTERS				= 'soundboard.ddb_monsters_about',
	KNICKERS				= 'soundboard.ddb_nicktashas_knickers',
	NO						= 'soundboard.ddb_no',
	TWENTY					= 'soundboard.ddb_twenty_years_preparing',
	PATIENT					= 'soundboard.ddb_we_will_be_patient',
	FAILED					= 'soundboard.ddb_you_have_failed_me',
	BEDEAD					= 'soundboard.ddb_you_will_be_dead',
	LEVEL					= 'soundboard.next_level',
	CRYBABY					= 'soundboard.crybaby',
	CHARGE					= 'soundboard.2021.banjo_charge',
	CHOO					= 'soundboard.2021.choo_choo',
	UHOH					= 'soundboard.2021.uh_oh',
	DING					= 'soundboard.ding_ding',
	OW						= 'soundboard.ow',
	YAHOO					= 'soundboard.yahoo',
	KOOKA					= 'soundboard.ti9.kookaburra',
	NINETYNINE				= 'soundboard.glados.probability_99',
	MOMMY					= 'soundboard.ti3.kor_immortality',
	ROSHAN2					= 'soundboard.ti3.kor_roshan',
	DT1						= 'soundboard.diretide2020.reward1',
	DT2						= 'soundboard.diretide2020.reward2',
	DT3						= 'soundboard.diretide2020.reward3',
	DT4						= 'soundboard.diretide2020.reward4',
	DT5						= 'soundboard.diretide2020.reward5',
	DT6						= 'soundboard.diretide2020.reward6',
	DT7						= 'soundboard.diretide2020.reward7',
	CRICKET					= 'soundboard.cricket',
	FROG					= 'soundboard.frog',
	SKEETER					= 'soundboard.ti9.skeeter',
	MONKEY					= 'soundboard.ti9.monkey_biz',
	TADA					= 'soundboard.ti9.tada', 					--broken
	AWWW					= 'soundboard.ti9.crowd_groan',
	BOCK					= 'soundboard.ti10eventgame.reward4',
	RETREAT					= 'soundboard.fall2021eventgame.reward3',
	NOOO					= 'soundboard.fall2021eventgame.reward5',
	FRIEND					= 'soundboard.fall2021eventgame.reward6', 	--broken
	HOTCHILLI				= 'soundboard.fall2021eventgame.reward2',
	GOODGOOD				= 'soundboard.fall2021eventgame.reward4',
	-- CASTER
	YUNO					= 'teamfandom.ti2021.Yuno',
	WEPPAS					= 'teamfandom.ti2021.Weppas',
	TSUNAMI					= 'teamfandom.ti2021.Tsunami',
	TEAGUVNOR				= 'teamfandom.ti2021.Teaguvnor',
	PYRIONFLAX				= 'teamfandom.ti2021.Pyrionflax',
	PURGE					= 'teamfandom.ti2021.Purge',
	PPD						= 'teamfandom.ti2021.PPD',
	PIMPMUCKL				= 'teamfandom.ti2021.Pimpmuckl',
	LYRICAL					= 'teamfandom.ti2021.Lyrical',
	LACOSTE					= 'teamfandom.ti2021.Lacoste',
	JENKINS					= 'teamfandom.ti2021.Jenkins',
	HOTBID					= 'teamfandom.ti2021.Hotbid',
	GARETH					= 'teamfandom.ti2021.Gareth',
	DAKOTA					= 'teamfandom.ti2021.Dakota',
	AUI						= 'teamfandom.ti2021.Aui_2000',
	AVO						= 'teamfandom.ti2021.Avo',
	SLACKS					= 'teamfandom.ti2021.Siractionslacks',
	EPHEY					= 'teamfandom.ti2021.Ephey',
	FOGGED					= 'teamfandom.ti2021.Fogged',
	LYRICAL					= 'teamfandom.ti2021.Lyrical',
	CAP						= 'teamfandom.ti2021.Cap',
	ODPIXEL					= 'teamfandom.ti2021.ODPixel',
	-- SUPPORTER'S CLUB / TEAMFANCONTENT
	KACHING					= 'teamfandom.9.8255888.142504',
	DIEDIE					= 'teamfandom.8.8261882.142156',
	HOWDAREU				= 'teamfandom.8.1838315.142114',
	MMM						= 'teamfandom.7.8172181.141854',
	NO3						= 'teamfandom.9.1061269.142638',
	DUB						= 'teamfandom.9.8894818.142443',
	MID						= 'teamfandom.9.8597391.142395',
	DEST					= 'teamfandom.9.8376426.142327',
	ESCAPE					= 'teamfandom.9.2586976.142488',
	DINGDONG				= 'teamfandom.9.7584152.142462',
	YABOI					= 'teamfandom.9.7554697.142388',
	CANTPAUSE				= 'teamfandom.5.8376426.141031',
	BKB						= 'teamfandom.5.2163.140930',
	IDC						= 'teamfandom.5.2586976.140998',
	WRONG					= 'teamfandom.5.2586976.140999',
	XD						= 'teamfandom.5.7390454.141104',
	JENKINS2				= 'teamfandom.5.8180753.140947',
	LOVE					= 'teamfandom.5.8180753.140949',
	FORME					= 'teamfandom.5.8261648.141161',
	TALENTED				= 'teamfandom.5.8261648.141162',
	HOTSKILLS				= 'teamfandom.5.8261648.141163',
	CALM					= 'teamfandom.5.8272699.141025',
	SMOKERINOS				= 'teamfandom.5.8272699.141026',
	HECK					= 'teamfandom.5.8272699.141027',
	WATCHTHIS				= 'teamfandom.5.8318683.141143',
	CHILL					= 'teamfandom.5.8597391.141014',
	BREATHS					= 'teamfandom.5.8597391.141015',
	HELLO					= 'teamfandom.5.8605863.140936',
	PANIC					= 'teamfandom.5.8605863.140935',
	LOLGIRL					= 'teamfandom.5.8721219.141078',
	BUTTONS					= 'teamfandom.5.46.141045',
	WHATHAPPEN				= 'teamfandom.5.8740972.141296',
	AIYO					= 'teamfandom.5.4.141156',
	DISGUY					= 'teamfandom.5.8169775.141197',
	WAOWAMAZING				= 'teamfandom.5.7356881.141262',
	STOPFIGHTING			= 'teamfandom.5.7356881.141263',
	WHYMUTE					= 'teamfandom.5.7356881.141264',
	GOODBYE					= 'teamfandom.5.726228.141230',
	PLEASESIR				= 'teamfandom.5.111474.140943',
	ALLIGATOR				= 'teamfandom.5.8261554.141216',
	AYAYA					= 'teamfandom.5.8390848.141280',
	GOBLIN					= 'teamfandom.5.8260983.140968',
	VIOLENCE				= 'teamfandom.6.8728920.141396',
	NOTBSJ					= 'teamfandom.6.2586976.141340',
	--TI11
	OMG						= 'soundboard.oh_my_god_woo',
	CUTE					= 'soundboard.oh_very_cute',
	RAMPAGE					= 'soundboard.rrrrrampage',
	WAOW					= 'soundboard.wow_cn',
	SOBIG					= 'soundboard.his_brain_is_so_big',
	BOOM					= 'soundboard.chick_chick_boom',
	RULOL					= 'soundboard.casperrr_laugh_ru',
	LOVEDOTA				= 'soundboard.i_love_dota_so_much',
	PERFECTO				= 'soundboard.wombo_combo_perfecto',
	BUCKET					= 'soundboard.agh_bucketentrance02',
	FIGHT					= 'soundboard.fight_fight_fight',
	--TI 11 TALENT
	SHEEP					= 'stickers.season6.97577101',
	KEKW					= 'stickers.season6.54535035',
	GODGAMER				= 'stickers.season6.68186278',
	WHATUP					= 'stickers.season6.136780564',
	KIDDOS					= 'stickers.season6.152618977',
	SORRY					= 'stickers.season6.196628643',
	UPSETY					= 'stickers.season6.41475731',
	OHNO					= 'stickers.season6.58380135',
	HABITAT					= 'stickers.season6.68243195',
	HERALD					= 'stickers.season6.87264171',
	JENKINS3				= 'stickers.season6.95145869',
	WEDGIEGOOSE				= 'stickers.season6.179308177',
	HELPING					= 'stickers.season6.256125365',
	HUAHUA					= 'stickers.season6.34438121',
	SUNS					= 'stickers.season6.690740',
	OIHEHE					= 'stickers.season6.104196230',

	-- HERO SOUNDS (HERO MUST BE PICKED TO PLAY HERO SOUNDS. HERO SOUNDS WILL NOT PLAY UNTIL STRATEGY TIME BEGINS IN THE LOBBY)

	-- ABADDON
	-- ALCHEMIST (ALCH)
	-- ANCIENT APPARITION (AA)
	-- ANTI-MAGE (AM)
	AMBLINK					= 'antimage_anti_blink_01',
	AMLOL					= 'antimage_anti_laugh_05',
	ABOMINATION				= 'antimage_anti_magicuser_01',
	-- ARC WARDEN
	SELF					= 'arc_warden_arcwar_respawn_07',
	-- AXE
	-- BANE
	BLINK					= 'bane_bane_blink_03',
	SLURP					= 'bane_bane_ability_brainsap_01',
	NO1						= 'bane_bane_deny_01',
	DEATHDREAM				= 'bane_bane_kill_06',
	WELCOME					= 'bane_bane_kill_05',
	YESS					= 'bane_bane_level_05',
	BANESPAZOUT				= 'bane_bane_level_06',
	BANECOIL				= 'bane_bane_rival_10',
	RAWFISH					= 'bane_bane_rival_12',
	DREAMY					= 'bane_bane_scepter_02',
	-- BATRIDER
	-- BEASTMASTER
	-- BLOODSEEKER
	-- BOUNTY HUNTER (BH)
	DAMNIT					= 'bounty_hunter_bount_ability_failure_07',
	TOOBAD					= 'bounty_hunter_bount_deny_06',
	TRANSACTION				= 'bounty_hunter_bount_lasthit_07',
	BHLOL					= 'bounty_hunter_bount_laugh_02',
	FIIR					= 'bounty_hunter_bount_move_11',
	ITAMGRO					= 'bounty_hunter_bount_move_18',
	AHGOPRIRA				= 'bounty_hunter_bount_move_19',
	-- BREWMASTER
	-- BRISTLEBACK
	-- BROODMOTHER
	-- CENTAUR WARRUNNER
	-- CHAOS KNIGHT (CK)
	FUNDAMENTAL				= 'chaos_knight_chaknight_rare_05',
	CKLOL2					= 'chaos_knight_chaknight_laugh_17',
	CKLOL					= 'chaos_knight_chaknight_laugh_15',
	-- CHEN
	-- CLINKZ
	-- CLOCKWERK
	-- CRYSTAL MAIDEN (CM)
	HELLBITCH				= 'crystalmaiden_cm_lina_09',
	GLACIER					= 'crystalmaiden_cm_kill_05',
	BREATH					= 'crystalmaiden_cm_kill_10',
	URDEAD					= 'crystalmaiden_cm_kill_13',
	CMLOL					= 'crystalmaiden_cm_laugh_06',
	BUSTED					= 'crystalmaiden_cm_rival_18',
	-- DARK SEER
	-- DARK WILLOW
	-- DAWNBREAKER (DB)
	SILLY					= 'dawnbreaker_valora_ally_143',
	WHO						= 'dawnbreaker_valora_ally_121',
	RATIO					= 'dawnbreaker_valora_ally_076',
	-- DAZZLE
	-- DEATH PROPHET (DP)
	-- DISRUPTOR
   DROOD					= 'disruptor_dis_move_10',
   KILLME					= 'disruptor_dis_underattack_02',
	-- DOOM
	-- DRAGON KNIGHT
	-- DROW RANGER
	-- EARTH SPIRIT
	-- EARTHSHAKER (ES)
	SLAMMIN					= 'earthshaker_erth_ability_echo_06',
	ECHO					= 'earthshaker_erth_ability_echo_07',
	POUNDU					= 'earthshaker_erth_attack_08',
	FAULT					= 'earthshaker_erth_kill_08',
	SHAKEIT					= 'earthshaker_erth_attack_03',
	TREMBLE					= 'earthshaker_erth_move_16',
	-- ELDER TITAN
	-- EMBER SPIRIT
	-- ENCHANTRESS
	-- ENIGMA
	-- FACELESS VOID
	-- GRIMSTROKE
	-- GYROCOPTER
	LAWN					= 'gyrocopter_gyro_deny_05',
	ROT						= 'gyrocopter_gyro_kill_16',
	NAP						= 'gyrocopter_gyro_kill_05',
	GYRODK					= 'gyrocopter_gyro_rival_04',
	GYROVIPER				= 'gyrocopter_gyro_ally_01',
	GYROJAK					= 'gyrocopter_gyro_ally_03',
	GEGEGA					= 'gyrocopter_gyro_attack_18',
	BEAK					= 'gyrocopter_gyro_cast_01',
	DAMNKIDS				= 'gyrocopter_gyro_death_10',
	SWALLOW					= 'gyrocopter_gyro_death_11',
	UHMSHIT					= 'gyrocopter_gyro_death_14',
	UHMSHIT2				= 'gyrocopter_gyro_death_16',
	SONSAB					= 'gyrocopter_gyro_death_17',
	DAMMIT					= 'gyrocopter_gyro_failure_01',
	FORGETTING				= 'gyrocopter_gyro_homing_missile_fire_02',
	RATATAT					= 'gyrocopter_gyro_kill_07',
	GYROLOL					= 'gyrocopter_gyro_laugh_11',
	BARREL					= 'gyrocopter_gyro_level_12',
	GRUMBLE					= 'gyrocopter_gyro_move_27',
	FLYBY					= 'gyrocopter_gyro_respawn_08',
	CREEPS					= 'gyrocopter_gyro_rival_18',
	RAINING					= 'gyrocopter_gyro_rocket_barrage_04',
	-- HOODWINK (HW)
	NUTBUSTER				= 'hoodwink_hoodwink_acorn_en_06',
	WARMFUZZY				= 'hoodwink_hoodwink_acorn_en_15',
	THINKING				= 'hoodwink_hoodwink_ally_133',
	DRESS					= 'hoodwink_hoodwink_ally_153',
	TELLU					= 'hoodwink_hoodwink_ally_169',
	COMPARTMENTALIZE		= 'hoodwink_hoodwink_ally_197',
	SQUIRRELDRAGON			= 'hoodwink_hoodwink_ally_231',
	PORNSTAR				= 'hoodwink_hoodwink_ally_301',
	LITTLEKILLER			= 'hoodwink_hoodwink_ally_39',
	MYTAIL					= 'hoodwink_hoodwink_ally_63',
	RELISH					= 'hoodwink_hoodwink_arb_hit_08',
	BINGO					= 'hoodwink_hoodwink_arb_hit_10',
	HOODHELLO				= 'hoodwink_hoodwink_arb_hit_15',
	AWWNUTS					= 'hoodwink_hoodwink_arb_miss_04',
	CHINUP					= 'hoodwink_hoodwink_arbalest_09',
	YEAHNAH					= 'hoodwink_hoodwink_attack_08',
	GETSTUFFED				= 'hoodwink_hoodwink_attack_09',
	YEPYEP					= 'hoodwink_hoodwink_bottle_03',
	CITYFOLK				= 'hoodwink_hoodwink_cityfolk_01_02',
	LASTLAUGH				= 'hoodwink_hoodwink_curse_06',
	GENUINE					= 'hoodwink_hoodwink_death_02',
	CUZ						= 'hoodwink_hoodwink_deny_08',
	STILLNAH				= 'hoodwink_hoodwink_deny_pain_01',
	MURDER					= 'hoodwink_hoodwink_idle_01',
	KILLKILLKILL			= 'hoodwink_hoodwink_idle_02',
	HOWZIT					= 'hoodwink_hoodwink_idle_05',
	NEST					= 'hoodwink_hoodwink_kill_23',
	SWEETASS				= 'hoodwink_hoodwink_lasthit_09',
	HOODLOL					= 'hoodwink_hoodwink_laugh_11',
	ALWAYS					= 'hoodwink_hoodwink_net_hit_04',
	STUFFIES				= 'hoodwink_hoodwink_net_hit_07',
	BLEEDOUT				= 'hoodwink_hoodwink_net_hit_08',
	MUPPET					= 'hoodwink_hoodwink_rival_139',
	SILLYBASTARD			= 'hoodwink_hoodwink_rival_140',
	LITTERING				= 'hoodwink_hoodwink_wheel_all_12',
	-- HUSKAR
	B4B						= 'huskar_husk_ability_lifebrk_06',
	GIVEITUP				= 'huskar_husk_kill_08',
	HUSKLOL					= 'huskar_husk_laugh_05',
	-- INVOKER
	FIGHTME					= 'invoker_invo_attack_05',
	CARL					= 'invoker_invo_rare_04',
	-- IO
	-- JAKIRO
	CHEERS					= 'jakiro_jak_bottle_01',
	PEPPERS					= 'jakiro_jak_brother_05',
	BURNINATED				= 'jakiro_jak_deny_12',
	JAKLOL					= 'jakiro_jak_deny_15',
	CHANGES					= 'jakiro_jak_rare_03',
	ICENFIRE				= 'jakiro_jak_ability_dual_01',
	-- JUGGERNAUT
	MASK					= 'juggernaut_jug_rare_04',
	BITCH					= 'juggernaut_jug_rare_06',
	-- KEEPER OF THE LIGHT (KOTL)
	KOTLLAWN				= 'keeper_of_the_light_keep_deny_12',
	KOTLNAY					= 'keeper_of_the_light_keep_deny_16',
	-- KUNKKA
	FAILBOAT				= 'kunkka_kunk_ability_failure_02',
	SWEETLY					= 'kunkka_kunk_ally_04',
	KUNKSVEN				= 'kunkka_kunk_ally_07',
	KUNKSAND				= 'kunkka_kunk_attack_08',
	CATSWING				= 'kunkka_kunk_attack_09',
	CHUM					= 'kunkka_kunk_kill_11',
	SETSAIL					= 'kunkka_kunk_kill_13',
	KUNKTIDE				= 'kunkka_kunk_killspecial_02',
	BOOTY					= 'kunkka_kunk_last_04',
	KUNKLOL					= 'kunkka_kunk_laugh_06',
	KUNKLOL1				= 'kunkka_kunk_laugh_07',
	KUNKLOL2				= 'kunkka_kunk_laugh_02',
	JIB						= 'kunkka_kunk_move_10',
	TREEWEASELS				= 'kunkka_kunk_rare_02',
	KUNKTIDE2				= 'kunkka_kunk_rival_14',
	KUNKTIDE1				= 'kunkka_kunk_rival_22',
	SOULMATE				= 'kunkka_kunk_rival_25',
	KUNKTIDE3				= 'kunkka_kunk_rival_27',
	KUNKHELLO				= 'kunkka_kunk_thanks_02',
	TRUSTY					= 'kunkka_kunk_thanks_03',
	-- LEGION COMMANDER (LC)
	SMELLS					= 'legion_commander_legcom_rare_01',
	DUMB_BASTARD			= 'legion_commander_legcom_rare_03',
	BLEED					= 'legion_commander_legcom_attack_14',
	DANCE					= 'legion_commander_legcom_duel_05',
	TEAR					= 'legion_commander_legcom_duel_08',
	DITCH					= 'legion_commander_legcom_rival_01',
	LEGIONLOL				= 'legion_commander_legcom_laugh_05',
	MUSTACHE				= 'legion_commander_legcom_ally_11',
	-- LESHRAC
	-- LICH
	FROSTY					= 'lich_lich_ability_armor_01',
	FROZE					= 'lich_lich_ability_chain_03',
	AINTNICE				= 'lich_lich_ability_nova_05',
	GREATERGOOD				= 'lich_lich_ability_ritual_01',
	COME2LICH				= 'lich_lich_ability_ritual_05',
	NUMNUM					= 'lich_lich_ability_ritual_07',
	YOMANA					= 'lich_lich_ability_ritual_13',
	TINGLE					= 'lich_lich_attack_03',
	CHASEU					= 'lich_lich_cast_03',
	WATCHURSTEP				= 'lich_lich_kill_05',
	GRASS					= 'lich_lich_kill_06',
	LICHLOL					= 'lich_lich_deny_09',
	-- LIFESTEALER
	-- LINA
	FIREBALL				= 'lina_lina_ability_lightstrike_03',
	SISTERS					= 'lina_lina_ally_07',
	COLDBITCH				= 'lina_lina_cm_03',
	MELTIN					= 'lina_lina_cm_12',
	ADOPTED					= 'lina_lina_cm_15',
	AWW						= 'lina_lina_deny_17',
	LINALOL					= 'lina_lina_laugh_04',
	LINALOL1				= 'lina_lina_laugh_07',
	LINALOL2				= 'lina_lina_laugh_10',
	COME2MAMA				= 'lina_lina_purch_02',
	COOKBOOK				= 'lina_lina_rival_12',
	FISHDICKS				= 'lina_lina_rival_14',
	IMHOT					= 'lina_lina_spawn_09',
	URHOT					= 'lina_lina_thanks_02',
	-- LION
	-- LONE DRUID (LD)
	-- LUNA
	WOODS					= 'luna_luna_kill_06',
	NOVA					= 'luna_luna_rare_02',
	-- LYCAN
	-- MAGNUS
	-- MARCI
	MARCI					= 'marci_marci_immortality',
	-- MEDUSA
	-- MEEPO
	-- MIRANA
	-- MONKEY KING (MK)
	-- MORPHLING
	-- MUERTA
	-- NAGA SIREN
	-- NATURE'S PROPHET (NP)
	-- NECROPHOS
	-- NIGHT STALKER (NS)
	-- NYX ASSASSIN (NYX)
	-- OGRE MAGI
	EEYAA					= 'ogre_magi_ogmag_bloodlust_04',
	PRACTICE				= 'ogre_magi_ogmag_ability_multi_02',
	HITTINSTUFF				= 'ogre_magi_ogmag_attack_04',
	OGREHEY					= 'ogre_magi_ogmag_attack_11',
	OGRELOL					= 'ogre_magi_ogmag_laugh_04',
	OGRELOL1				= 'ogre_magi_ogmag_laugh_03',
	OGRELOL2				= 'ogre_magi_ogmag_laugh_06',
	THINKIN					= 'ogre_magi_ogmag_level_05',
	RUNNING					= 'ogre_magi_ogmag_move_20',
	SQUIRREL				= 'ogre_magi_ogmag_move_22',
	OUTSMARTED				= 'ogre_magi_ogmag_rival_07',
	HESDEAD					= 'ogre_magi_ogmag_rival_20',
	LEVELS					= 'ogre_magi_ogmag_level_06',
	SMARTER					= 'ogre_magi_ogmag_level_03',
	-- OMNIKNIGHT
	-- ORACLE
	-- OUTWORLD DEVOURER (OD)
	-- PANGOLIER
	PANLOL1					= 'pangolin_pangolin_laugh_14',
	PANLOL2					= 'pangolin_pangolin_laugh_07',
	PANLOL3					= 'pangolin_pangolin_laugh_09',
	-- PHANTOM ASSASSIN (PA)
	PALOL					= 'phantom_assassin_phass_laugh_07',
	PALOL1					= 'phantom_assassin_phass_laugh_04',
	NONONO					= 'phantom_assassin_phass_deny_14',
	GREEDY					= 'phantom_assassin_phass_lasthit_10',
	DIVINE					= 'phantom_assassin_phass_happy_09',
	-- PHANTOM LANCER
	-- PHOENIX
	-- PRIMAL BEAST
	-- PUCK
	-- PUDGE
	-- PUGNA
	-- QUEEN OF PAIN (QOP)
	QOPBLINK				= 'queenofpain_pain_blink_01',
	SAFE					= 'queenofpain_pain_kill_05',
	LITTLED					= 'queenofpain_pain_kill_10',
	PERF					= 'queenofpain_pain_kill_12',
	DIDUSAY					= 'queenofpain_pain_kill_13',
	QOPHA					= 'queenofpain_pain_laugh_13',
	QOPLOL					= 'queenofpain_pain_laugh_04',
	ROLEPLAY				= 'queenofpain_pain_rare_01',
	ONES					= 'queenofpain_pain_rare_06',
	SUBMIT					= 'queenofpain_pain_specialcase_03',
	SOGOOD					= 'queenofpain_pain_taunt_02',
	-- RAZOR
	DEAD					= 'razor_raz_kill_03',
	ZAPPED					= 'razor_raz_kill_09',
	YOUCANRUN				= 'razor_raz_cast_01',
	-- RIKI
	-- RUBIK
	-- SAND KING (SK)
	SANDY					= 'sandking_skg_kill_09',
	SKLOL					= 'sandking_skg_laugh_10',
	SAND					= 'sandking_skg_rare_03',
	-- SHADOW DEMON (SD)
	-- SHADOW FIEND (SF)
	-- SHADOW SHAMAN
	HYAA					= 'shadowshaman_shad_ability_ether_03',
	KAWK					= 'shadowshaman_shad_ability_voodoo_06',
	CHICKEN					= 'shadowshaman_shad_ability_voodoo_08',
	HAHAHA					= 'shadowshaman_shad_blink_02',
	PRAYERS					= 'shadowshaman_shad_level_03',
	OTHERSIDE				= 'shadowshaman_shad_respawn_04',
	-- SILENCER
	SHUTUP					= 'silencer_silen_attack_07',
	HEARIT					= 'silencer_silen_attack_13',
	SHHNOW					= 'silencer_silen_kill_02',
	HURL					= 'silencer_silen_rival_02',
	NOISE					= 'silencer_silen_lose_04',
	SILENCERLOL				= 'silencer_silen_fastres_02',
	-- SKYWRATH MAGE
	-- SLARDAR
	SPAWNAGE				= 'slardar_slar_kill_07',
	SCHOOLED				= 'slardar_slar_kill_08',
	SLARLOL					= 'slardar_slar_laugh_05',
	SCALING					= 'slardar_slar_level_01',
	LONGWAY					= 'slardar_slar_longdistance_02',
	-- SLARK
	-- SNAPFIRE
	-- SNIPER
	HOHO					= 'sniper_snip_ability_shrapnel_03',
	DUMB					= 'sniper_snip_kill_05',
	HEHE					= 'sniper_snip_laugh_08',
	WANKER					= 'sniper_snip_tf2_02',
	PEEPED					= 'sniper_snip_ability_assass_04',
	GUN						= 'sniper_snip_kill_arrow_06',
	-- SPECTRE
	-- SPIRIT BREAKER
	-- STORM SPIRIT
	CHARMS					= 'stormspirit_stormspirit_rival_14',
	-- SVEN
	-- TECHIES
	-- TEMPLAR ASSASSIN (TA)
	MYSTERY					= 'templar_assassin_temp_rival_11',
	TALOL					= 'templar_assassin_temp_laugh_04',
	-- TERRORBLADE (TB)
	-- TIDEHUNTER
	FISHES					= 'tidehunter_tide_death_09',
	DROWN					= 'tidehunter_tide_kill_02',
	TIDINGS					= 'tidehunter_tide_kill_10',
	FISHFOOD				= 'tidehunter_tide_kill_12',
	ANCHOVY					= 'tidehunter_tide_level_04',
	PLESIOSAUR				= 'tidehunter_tide_level_24',
	WALRUS					= 'tidehunter_tide_level_18',
	KUNKKAA					= 'tidehunter_tide_rival_04',
	TIDEMORPH				= 'tidehunter_tide_rival_11',
	TIDEFIRE				= 'tidehunter_tide_rival_13',
	TIDEAXE					= 'tidehunter_tide_rival_19',
	TIDEWOMEN				= 'tidehunter_tide_rival_24',
	TIDELOL					= 'tidehunter_tide_laugh_01',
	TIDELOL1				= 'tidehunter_tide_laugh_06',
	TIDELOL2				= 'tidehunter_tide_laugh_07',
	-- TIMBERSAW
	-- TINKER
	-- TINY
	-- TREANT PROTECTOR
	-- TROLL WARLORD
	-- TUSK
	OKIE					= 'tusk_tusk_move_25',
	TUSKIE					= 'tusk_tusk_move_26',
	TUSKLOL					= 'tusk_tusk_kill_16',
	FISTBUMP				= 'tusk_tusk_kill_26',
	TUSKOK					= 'tusk_tusk_rival_19',
	-- UNDERLORD
	-- UNDYING
	-- URSA
	-- VENGEFUL SPIRIT
	-- VENOMANCER
	-- VIPER
	EJECTING				= 'viper_vipe_death_16',
	WONDER					= 'viper_vipe_kill_08',
	BLRHAHA					= 'viper_vipe_laugh_01',
	HAHABLR					= 'viper_vipe_laugh_07',
	ORB						= 'viper_vipe_orbofvenome_01',
	VHOLY					= 'viper_vipe_spawn_05',
	-- VISAGE
	-- WARLOCK (WL)
	SMOKED					= 'warlock_warl_kill_02',
	PIP						= 'warlock_warl_lasthit_02',
	UNFIEND					= 'warlock_warl_death_11',
	-- WEAVER
	-- WINDRANGER (WR)
	FANTASTIC				= 'windrunner_wind_ability_focusfire_04',
	BUHBYE					= 'windrunner_wind_ability_windrun_01',
	BLOWKISS				= 'windrunner_wind_attack_04',
	UGLYPAIN				= 'windrunner_wind_attack_06',
	GINGER					= 'windrunner_wind_death_05',
	BORRING					= 'windrunner_wind_fastres_02',
	WORSE					= 'windrunner_wind_kill_11',
	EZBREEZ					= 'windrunner_wind_lasthit_04',
	WRLOL					= 'windrunner_wind_laugh_08',
	WRLOL1					= 'windrunner_wind_laugh_10',
	HOPE					= 'windrunner_wr_arc_ally_189',
	-- WINTER WYVERN (WW)
	CHILLBB					= 'winter_wyvern_winwyv_deny_08',
	WHYOWHY					= 'winter_wyvern_winwyv_death_02',
	WWMELT					= 'winter_wyvern_winwyv_death_08',
	FANCYTHAT				= 'winter_wyvern_winwyv_death_10',
	WW1						= 'winter_wyvern_winwyv_anger_01',
	WW2						= 'winter_wyvern_winwyv_anger_02',
	WW13					= 'winter_wyvern_winwyv_anger_03',
	WW14					= 'winter_wyvern_winwyv_anger_04',
	WW5						= 'winter_wyvern_winwyv_anger_05',
	WW6						= 'winter_wyvern_winwyv_anger_08',
	WW7						= 'winter_wyvern_winwyv_anger_09',
	WW8						= 'winter_wyvern_winwyv_anger_10',
	WW9						= 'winter_wyvern_winwyv_happy_02',
	WW10					= 'winter_wyvern_winwyv_happy_03',
	WW11					= 'winter_wyvern_winwyv_happy_04',
	WW12					= 'winter_wyvern_winwyv_happy_05',
	WW13					= 'winter_wyvern_winwyv_happy_06',
	WW14					= 'winter_wyvern_winwyv_happy_07',
	-- WITCH DOCTOR (WD)
	LOOK2					= 'witchdoctor_wdoc_ability_cask_03',
	LOOK					= 'witchdoctor_wdoc_ability_cask_06',
	MALPRACTICE				= 'witchdoctor_wdoc_attack_07',
	BONE					= 'witchdoctor_wdoc_kill_11',
	WAIT4IT					= 'witchdoctor_wdoc_killspecial_01',
	POP						= 'witchdoctor_wdoc_killspecial_02',
	BIGMESS					= 'witchdoctor_wdoc_killspecial_03',
	BIT						= 'witchdoctor_wdoc_level_06',
	FEELINGOOD				= 'witchdoctor_wdoc_level_08',
	HARM					= 'witchdoctor_wdoc_rare_03',
	OYA						= 'witchdoctor_wdoc_laugh_03',
	-- WRAITH KING (WK)
	HUAGH					= 'skeleton_king_wraith_ability_hellfire_07',
	GUYS					= 'skeleton_king_wraith_ability_incarn2_01',
	GOING					= 'skeleton_king_wraith_ability_incarn2_03',
	PUNY					= 'skeleton_king_wraith_ally_01',
	MANOFMEAT				= 'skeleton_king_wraith_ally_02',
	KNEE					= 'skeleton_king_wraith_attack_03',
	BLINKKING				= 'skeleton_king_wraith_blink_02',
	QUEEN					= 'skeleton_king_wraith_death_06',
	HEIRS					= 'skeleton_king_wraith_death_05',
	WITHSCREAMING			= 'skeleton_king_wraith_death_20',
	REGICIDE				= 'skeleton_king_wraith_death_long_07',
	WKBRB					= 'skeleton_king_wraith_death_long_17',
	TUT						= 'skeleton_king_wraith_deny_05',
	BADPEASANT				= 'skeleton_king_wraith_deny_15',
	ALLTHESEX				= 'skeleton_king_wraith_items_02',
	BALLIN					= 'skeleton_king_wraith_items_18',
	PROSTRATE				= 'skeleton_king_wraith_kill_05',
	TRIBUTE					= 'skeleton_king_wraith_kill_09',
	COUP					= 'skeleton_king_wraith_kill_14',
	DECEASED				= 'skeleton_king_wraith_kill_15',
	PERMISSION				= 'skeleton_king_wraith_lasthit_14',
	WKLOL					= 'skeleton_king_wraith_laugh_02',
	WKNO					= 'skeleton_king_wraith_lose_01',
	SWAGGER					= 'skeleton_king_wraith_move_08',
	MYBITCH					= 'skeleton_king_wraith_move_09',
	RAGEKING				= 'skeleton_king_wraith_spawn_04',
	-- ZEUS
	HEAVEN					= 'zuus_zuus_ability_thunder_02',
	EXIST					= 'zuus_zuus_rare_04',
	TRUST					= 'zuus_zuus_rare_05',

	AsianCasters =
	{
		'soundboard.tian_huo',
		'soundboard.wan_bu_liao_la',
		'soundboard.jia_you',
		'soundboard.po_liang_lu',
		'soundboard.zou_hao_bu_song',
		'soundboard.gao_fu_shuai',
		'soundboard.duiyou_ne',
		'soundboard.hu_lu_wa',
		'soundboard.liu_liu_liu',
		'soundboard.ni_qi_bu_qi',
		'soundboard.ta_daaaa',
		'soundboard.oy_oy_oy',
		'soundboard.next_level',
		'soundboard.easiest_money',
		'soundboard.echo_slama_jama',
	},

	EnglishCasters =
	{
		'soundboard.holy_moly',
		'soundboard.patience',
		'soundboard.all_dead',
		'soundboard.wow',
		'soundboard.brutal',
		'soundboard.playing_to_win',
		'soundboard.that_was_questionable',
		'soundboard.what_just_happened',
		'soundboard.youre_a_hero',
		'soundboard.absolutely_perfect',
		'soundboard.glados.disappointed',
		'soundboard.looking_spicy',
		'soundboard.coming_through_with_the_woooo',
		'soundboard.nothing_that_can_stop_this_man',
		'soundboard.oh_my_god_what_oh_oh',
		'soundboard.see_you_later_nerds',
		'soundboard.what_the_f_just_happened',
	},

	CisCasters =
	{
		'soundboard.ay_ay_ay',
		'soundboard.eto_prosto_netchto',
		'soundboard.ehto_g_g',
		'soundboard.bozhe_ti_posmotri',
		'soundboard.oy_oy_bezhat',
		'soundboard.eto_sochno',
		'soundboard.krasavchik',
		'soundboard.bozhe_kak_eto_bolno',
		'soundboard.eto_nenormalno',
		'soundboard.kreasa_kreasa',
		'soundboard.kak_boyge_te_byechenya',
		'soundboard.eto_ge_popayx_feeda',
		'soundboard.wot_eto_bru',
		'soundboard.da_da_da_nyet',
		'soundboard.a_net_net_da',
		'soundboard.a_nu_ka_idi_suda',
		'soundboard.aaah_aaah_chto',
		'soundboard.chto_eto_kakaya_zhest',
		'soundboard.eto_takaya_dushka',
		'soundboard.takaya_haliava',
	},

	FretsFavorites =
	{
		'soundboard.da_da_da_nyet',
		'soundboard.a_nu_ka_idi_suda',
		'soundboard.aaah_aaah_chto',
		'soundboard.krasavchik',
		'soundboard.wan_bu_liao_la',
		'soundboard.jia_you',
		'soundboard.duiyou_ne',
		'soundboard.ta_daaaa',
		'soundboard.oy_oy_oy',
		'soundboard.next_level',
		'soundboard.nakupuuu',
		'soundboard.ay_ay_ay_cn',
		'soundboard.hui_tian_mie',
		'soundboard.tiao_zou_le',
		'teamfandom.ti2021.Siractionslacks',
	},

	GoodSounds =
	{
		'soundboard.holy_moly',
		'soundboard.patience',
		'soundboard.all_dead',
		'soundboard.playing_to_win',
		'soundboard.youre_a_hero',
		'soundboard.looking_spicy',
		'soundboard.coming_through_with_the_woooo',
		'soundboard.nothing_that_can_stop_this_man',
		'soundboard.see_you_later_nerds',
		'soundboard.ta_daaaa',
		'soundboard.next_level',
		'soundboard.easiest_money',
		'soundboard.echo_slama_jama',
		'soundboard.nakupuuu',
		'soundboard.hui_tian_mie',
		'soundboard.tiao_zou_le',
	},

	BadSounds =
	{
		'soundboard.brutal',
		'soundboard.that_was_questionable',
		'soundboard.what_just_happened',
		'soundboard.glados.disappointed',
		'soundboard.oh_my_god_what_oh_oh',
		'soundboard.see_you_later_nerds',
		'soundboard.what_the_f_just_happened',
		'soundboard.ni_qi_bu_qi',
		'soundboard.piao_liang',
		'soundboard.bai_tuo_shei_qu',
		'soundboard.ay_ay_ay_cn',
		'soundboard.ay_ay_ay',
		'soundboard.eto_prosto_netchto',
		'soundboard.ehto_g_g',
		'soundboard.bozhe_kak_eto_bolno',
		'soundboard.eto_nenormalno',
		'soundboard.kreasa_kreasa',
		'soundboard.wot_eto_bru',
		'soundboard.da_da_da_nyet',
		'soundboard.a_net_net_da',
		'soundboard.a_nu_ka_idi_suda',
		'soundboard.aaah_aaah_chto',
		'teamfandom.ti2021.Siractionslacks',
	}
}

return sounds